title: JINN/Z NOTES
description: Notes on Stuff

header_pages:
  - index.md
  - prj.md
  - abt.md
  - _posts

permalink: /:title
footer: '(c) 2026 - JINN/Z'

plugins:
  - jekyll-seo-tag

style: hacker
disable_google_fonts: true

tracking:
   script_src: "https://plausible.io/js/pa-OpLRUqU-eAWPy6_fvX79O.js"
   async: true
   defer: false
  
csp_extra: "script-src 'self' https://plausible.io; connect-src 'self' https://plausible.io;"
